title: TA-LHK | Technical Artist Portfolio
description: Unreal Engine 5.6 기반 Technical Artist 포트폴리오

show_downloads: false
google_analytics:

collections:
  optimization:
    output: true
    permalink: /optimization/:path/
  shader:
    output: true
    permalink: /shader/:path/
  pcg:
    output: true
    permalink: /pcg/:path/

defaults:
  - scope:
      path: ""
      type: optimization
    values:
      layout: post
  - scope:
      path: ""
      type: shader
    values:
      layout: post
  - scope:
      path: ""
      type: pcg
    values:
      layout: post
